project:
  type: website
  output-dir: docs

website:
  title: "SPEAK Lab"
  navbar:
    title: " 
  ![](/Images/Logo.png){width=45}
  \\ \\
  SPEAK Lab"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Team"
        href: team.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Blog"
        href: blog.qmd
  page-footer: 
    left: "" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: instagram 
        href: https://www.instagram.com/speaklaboratory/

format:
  html:
    theme: cosmo
    css: /styles.css
    toc: true
    metadata:
      pagetitle: "SPEAK Lab"

editor: visual

